import { FieldColorModeId, ThresholdsMode } from '@grafana/data';
import type { PresetCatalog } from '../../shared/presets';
import { DEFAULT_OPTIONS, type GaugeOptions } from './types';

/** Quick start presets for the Power Gauge. */
export const GAUGE_PRESETS: PresetCatalog<GaugeOptions> = {
  defaults: DEFAULT_OPTIONS,
  keep: ['fieldName', 'demoData'],
  presets: [
    {
      id: 'signed-power',
      label: 'Signed power, live',
      description: 'Zero mark on the ring, fill grows both ways, streaming history that keeps moving between refreshes.',
      icon: 'bolt',
      options: {
        historySource: 'stream',
        streamDuration: 60,
        secondaryText: 'Avg. {value}',
        secondaryReducer: 'mean',
        subtitleText: 'Past 15 min',
      },
      fieldConfig: {
        unit: 'kwatt',
        decimals: 1,
        min: -50,
        max: 200,
        color: { mode: FieldColorModeId.Fixed, fixedColor: 'orange' },
      },
    },
    {
      id: 'thresholds-300',
      label: '300° arc with thresholds',
      description: 'Near-full ring, linear scale, fill and history coloured by the standard thresholds; peak as the second line.',
      icon: 'circle',
      options: {
        startAngle: 120,
        sweepAngle: 300,
        clockwise: true,
        scale: 'linear',
        ringWidth: 6,
        glow: 16,
        colorMode: 'thresholds',
        historyColorMode: 'thresholds',
        fadeHistory: false,
        secondaryText: 'Peak {value}',
        secondaryReducer: 'max',
        subtitleText: 'Last 15 min',
        titlePosition: 'bottom',
      },
      fieldConfig: {
        unit: 'percent',
        decimals: 0,
        min: 0,
        max: 100,
        thresholds: {
          mode: ThresholdsMode.Absolute,
          steps: [
            { value: -Infinity, color: 'green' },
            { value: 55, color: 'orange' },
            { value: 80, color: 'red' },
          ],
        },
      },
    },
    {
      id: 'semicircle',
      label: 'Semicircle, net import/export',
      description: 'Half ring, custom tick values, blue/purple palette and a summed secondary line in energy units.',
      icon: 'exchange-alt',
      options: {
        startAngle: 180,
        sweepAngle: 180,
        clockwise: true,
        scale: 'linear',
        ringWidth: 7,
        glow: 18,
        positiveColor: 'blue',
        negativeColor: 'purple',
        tickMode: 'custom',
        tickValues: '-5, 0, 5, 10',
        secondaryText: 'Net {value}',
        secondaryReducer: 'sum',
        secondaryUnit: 'kwatth',
        secondaryDecimals: 1,
        subtitleText: 'Today',
        titlePosition: 'bottom',
      },
      fieldConfig: { unit: 'kwatt', decimals: 2, min: -5, max: 10 },
    },
    {
      id: 'last-samples-log',
      label: 'Last 60 samples, log scale',
      description: 'History of the newest samples instead of the time range, log compression and the field colour.',
      icon: 'chart-line',
      options: {
        scale: 'log',
        colorMode: 'field',
        historySource: 'lastN',
        historyPoints: 60,
        secondaryMode: 'text',
        secondaryText: 'Dashboard refresh: $__interval',
        subtitleText: 'Last 60 samples',
        titlePosition: 'top',
      },
      fieldConfig: { decimals: 0, color: { mode: FieldColorModeId.Fixed, fixedColor: 'dark-blue' } },
    },
    {
      id: 'static',
      label: 'Static, no history',
      description: 'Short 120° arc, large value, no chart and no animation: a plain, calm readout.',
      icon: 'pause',
      options: {
        startAngle: 210,
        sweepAngle: 120,
        clockwise: true,
        scale: 'linear',
        showHistory: false,
        animate: false,
        valueFontSize: 56,
        secondaryText: 'Range {value}',
        secondaryReducer: 'range',
        subtitleText: 'Over the visible range',
        titlePosition: 'hidden',
      },
      fieldConfig: { decimals: 1 },
    },
    {
      id: 'compact',
      label: 'Compact',
      description: 'For small tiles: no secondary line, soft glow, tick labels off.',
      icon: 'minus',
      options: { showSecondary: false, glow: 8, showTickLabels: false, subtitleText: '' },
      fieldConfig: { decimals: 0 },
    },
  ],
};
